# DL 1, Pytorch

Привет! На этом занятии мы познакомимся с PyTorch, с работой gpu и получением градиентов. В конце попробуем написать нейросеть для распознавания чисел.

**Для этого ноутбука надо включить GPU runtime**.

СЕМИНАР НАЧНЕТСЯ В 19:50.

In [1]:
import torch

In [4]:
torch.sqrt()

TypeError: sqrt() missing 1 required positional arguments: "input"

In [5]:
torch.*Tensor?

## Simple Pytorch

Изучим простые методы pytorch. Они сильно напоминают numpy, и часто можно использовать имя метода из numpy в pytorch.

In [6]:
t = torch.Tensor(2, 3, 4)

In [7]:
t

tensor([[[-6.9541e+18,  5.7733e-43, -6.9541e+18,  5.7733e-43],
         [-6.9540e+18,  5.7733e-43, -6.9540e+18,  5.7733e-43],
         [-6.9539e+18,  5.7733e-43, -6.9539e+18,  5.7733e-43]],

        [[-6.9536e+18,  5.7733e-43, -6.9538e+18,  5.7733e-43],
         [-6.9538e+18,  5.7733e-43, -6.9537e+18,  5.7733e-43],
         [-6.9538e+18,  5.7733e-43,  1.0194e-38,  4.6838e-39]]])

In [8]:
t.size(0)

2

In [9]:
t.random_(10)
t

tensor([[[0., 7., 1., 6.],
         [8., 5., 5., 3.],
         [4., 9., 4., 8.]],

        [[9., 2., 5., 7.],
         [2., 4., 7., 7.],
         [1., 9., 9., 1.]]])

In [10]:
t = torch.zeros_like(t)
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
t = torch.rand(2, 3, 4)
t

tensor([[[0.7101, 0.1967, 0.5200, 0.8067],
         [0.9568, 0.3224, 0.7951, 0.9611],
         [0.2170, 0.0105, 0.7171, 0.4930]],

        [[0.1108, 0.0580, 0.0942, 0.1874],
         [0.8863, 0.8174, 0.2015, 0.9754],
         [0.7790, 0.6151, 0.6973, 0.9648]]])

In [12]:
r = torch.Tensor(t)
r.resize_(3, 5)
r

tensor([[0.7101, 0.1967, 0.5200, 0.8067, 0.9568],
        [0.3224, 0.7951, 0.9611, 0.2170, 0.0105],
        [0.7171, 0.4930, 0.1108, 0.0580, 0.0942]])

In [13]:
a, b = torch.rand(1, 4), torch.rand(1, 4)
a + b

tensor([[0.5989, 1.6849, 1.7590, 1.5578]])

In [14]:
a * b

tensor([[0.0634, 0.7094, 0.7736, 0.5664]])

In [15]:
a @ b.T

tensor([[2.1127]])

In [16]:
a, b = torch.rand(3, 4), torch.rand(4, 5)
a @ b

tensor([[1.2197, 0.8031, 1.1221, 1.4834, 1.5925],
        [1.3367, 0.6396, 0.8047, 1.4512, 1.1489],
        [1.4014, 0.7885, 1.0671, 1.5999, 1.5676]])

In [17]:
a.norm(), b.sum() # np.linalg.norm

(tensor(2.3533), tensor(9.6808))

In [18]:
a / 10

tensor([[0.0568, 0.0965, 0.0332, 0.0918],
        [0.0654, 0.0554, 0.0841, 0.0041],
        [0.0549, 0.0785, 0.0686, 0.0708]])

In [19]:
torch.Tensor(3, 4, 5, 2).transpose(0, 2).shape

torch.Size([5, 4, 3, 2])

In [20]:
t = torch.arange(10)
t, t.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [21]:
t = t.to(torch.float32)
t, t.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

## Autograd & GPU

Теперь поработаем с GPU и получением градиентов.

In [22]:
a, b = torch.rand(3, 4), torch.rand(4, 5)
a, b

(tensor([[0.2144, 0.9962, 0.2524, 0.3129],
         [0.0325, 0.5885, 0.0330, 0.8060],
         [0.2659, 0.0042, 0.4692, 0.1306]]),
 tensor([[0.3173, 0.1484, 0.4082, 0.4997, 0.3845],
         [0.3403, 0.8317, 0.2661, 0.3067, 0.3620],
         [0.3870, 0.1338, 0.0227, 0.7302, 0.8586],
         [0.1649, 0.8932, 0.2139, 0.5526, 0.9306]]))

In [24]:
#a = a.to("cuda")

In [25]:
a @ b

tensor([[0.5564, 1.1736, 0.4253, 0.7699, 0.9509],
        [0.3563, 1.2186, 0.3431, 0.6663, 1.0040],
        [0.2889, 0.2224, 0.1482, 0.5489, 0.6281]])

In [26]:
#b = b.to("cuda")

In [27]:
a @ b

tensor([[0.5564, 1.1736, 0.4253, 0.7699, 0.9509],
        [0.3563, 1.2186, 0.3431, 0.6663, 1.0040],
        [0.2889, 0.2224, 0.1482, 0.5489, 0.6281]])

In [50]:
a.requires_grad_(True)

s = (a @ b).sum()
s

tensor(9.3010, grad_fn=<SumBackward0>)

In [52]:
s.backward()
s

tensor(9.3010, grad_fn=<SumBackward0>)

In [40]:
a, b

(tensor([[0.2144, 0.9962, 0.2524, 0.3129],
         [0.0325, 0.5885, 0.0330, 0.8060],
         [0.2659, 0.0042, 0.4692, 0.1306]], requires_grad=True),
 tensor([[0.3173, 0.1484, 0.4082, 0.4997, 0.3845],
         [0.3403, 0.8317, 0.2661, 0.3067, 0.3620],
         [0.3870, 0.1338, 0.0227, 0.7302, 0.8586],
         [0.1649, 0.8932, 0.2139, 0.5526, 0.9306]]))

In [41]:
a.grad, b.grad

(tensor([[5.2743, 6.3209, 6.3966, 8.2657],
         [5.2743, 6.3209, 6.3966, 8.2657],
         [5.2743, 6.3209, 6.3966, 8.2657]]),
 None)

In [42]:
s.grad

tensor(1.)

In [ ]:
a, b = torch.rand(3, 4, requires_grad=True), torch.rand(4, 5, requires_grad=True)
s = (a @ b).sum() 
s.backward()

In [ ]:
torch.as_tensor([0, 1, 2, 4, 5])

In [ ]:
a, b

## Neural Network


Давайте определим простую ML-задачу и попробуем решить её с помощью нейросети.

In [112]:
X = torch.rand(1000, 10)
w_true = torch.rand(10, 1) * 10
b_true = torch.tensor(3.1415926)
eps = torch.rand(1000) * 1e-3
y = X @ w_true + b_true + eps

In [113]:
w = torch.rand(10, 1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

In [114]:
X, y = X.to("cpu"), y.to("cpu")

In [93]:
y_hat = X @ w + b
L = ((y - y_hat)**2).mean()
L

tensor(821.6201, grad_fn=<MeanBackward0>)

In [94]:
L.backward()

In [95]:
w, w.grad, b, b.grad

(tensor([[0.8555],
         [0.2254],
         [0.8497],
         [0.2929],
         [0.8262],
         [0.8470],
         [0.1627],
         [0.8002],
         [0.3274],
         [0.0433]], requires_grad=True),
 tensor([[-29.0707],
         [-29.7811],
         [-28.9505],
         [-28.9953],
         [-27.5132],
         [-28.5548],
         [-28.1267],
         [-29.3516],
         [-30.5368],
         [-29.8530]]),
 tensor([0.4698], requires_grad=True),
 tensor([-56.2431]))

In [96]:
lr = 1e-2

with torch.inference_mode():
    w = w - w.grad * lr
    b = b - b.grad * lr
    #... # update w, b
w, w.grad, b, b.grad

(tensor([[1.1462],
         [0.5233],
         [1.1392],
         [0.5829],
         [1.1013],
         [1.1325],
         [0.4440],
         [1.0937],
         [0.6328],
         [0.3418]]),
 None,
 tensor([1.0322]),
 None)

In [101]:
for idx in range(5000):
    y_hat = X @ w + b
    L = ((y - y_hat)**2).mean()
    L.backward()
    with torch.inference_mode():
        w -= w - w.grad * lr
        b -= b - b.grad * lr

    if idx % 100 == 0:
        print(f"Current Loss: {L}")
        

Current Loss: 457.8040771484375


In [ ]:
torch.norm(w_true - w), torch.norm(b_true - b)

In [ ]:
w_true.tolist(), w.tolist()

In [ ]:
b_true, b

Воспользуемся высокоуровневым способ описывать нейросети в PyTorch:

In [115]:
class Linear(torch.nn.Module):
    def __init__(self, in_shape, out_shape):
        super().__init__()

        self.layer = torch.nn.Linear(in_shape, out_shape)
    
    def forward(self, x):
        return self.layer(x)

In [116]:
model = Linear(10, 1)
optimizer = torch.optim.SGD(model.parameters(), lr)
criterion = torch.nn.MSELoss()

In [104]:
#model = model.to("cuda")

In [121]:
#X = X.to("cuda")
#y = y.to("cuda")

for idx in range(100):
    y_hat = model(X)
    
    loss = criterion(y_hat, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    
    if idx % 100 == 0:
        print(f"Current Loss: {loss}")

Current Loss: 0.0564470998942852


In [122]:
list(model.parameters())

[Parameter containing:
 tensor([[0.1773, 0.5302, 1.1395, 4.1330, 7.4557, 9.0111, 2.1676, 6.4121, 5.6016,
          9.0968]], requires_grad=True),
 Parameter containing:
 tensor([4.3844], requires_grad=True)]

In [ ]:
# compare matrices

## MNIST

Перейдем к другой задаче -- распознавании чисел. Загрузим датасет MNIST и напишем нейросеть, которая отличает числа меньше 5 и больше или равно 5.

In [195]:
#!pip install keras
#!pip install tensorflow
from keras.datasets import mnist
import torch
import torch.nn as nn


(train_X, train_y), (test_X, test_y) = mnist.load_data()

In [196]:
print("\n".join(" ".join("X" if ch > 128 else "." for ch in row) for row in train_X[90].tolist()))

. . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . . . . X X . . . . . . . .
. . . . . . . . . . . . . . . . X X X X . . . . . . . .
. . . . . . . . . . . . . . . . X X X X . . . . . . . .
. . . . . . . . . . . . . . X X X X . . . . . . . . . .
. . . . . . . . . . . . . X X X . . . . . . . . . . . .
. . . . . . . . . . . . X X X . . . . . . . . . . . . .
. . . . . . . . . . X X X X . . . . . . . . . . . . . .
. . . . . . . . . . X X X . . . . . . . . . . . . . . .
. . . . . . . . . X X X . . . . . . . . . . . . . . . .
. . . . . . . . . X X X . . . . . . . . . . . . . . . .
. . . . . . . . X X X X . . . . . . . . X . . . . . . .
. . . . . . . . X X X . . . . . . . X X X X . . . . . .
. . . . . . . . X X X . . . . X X X X X X X . . . . . .
. . . . . . . X X X X . . X X X . . . X X X . . . . . .
. . . . . . . . X X X X . X X . . . . X X X . . . . . .
. . . . . . . . X X X X X X . . . X . X X X . . 

Создадим датасет для нашей задачи:

In [197]:
train_y[0]

5

In [198]:
X_train_tensor = torch.as_tensor(train_X) / 255
X_test_tensor = torch.as_tensor(test_X) / 255

y_train_tensor = torch.as_tensor(train_y < 5) * 1.0
y_test_tensor = torch.as_tensor(test_y < 5) * 1.0

In [199]:
y_train_tensor[0]

tensor(0.)

Опишем простую двухслойную сеть:

In [266]:
class NNClassifier(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.layer_0 = nn.Linear(28*28, 100)
        self.act_0 = nn.Tanh()
        self.layer_1 = nn.Linear(100, 1)
        self.act_1 = nn.Tanh()
    
    def forward(self, x):
        return self.act_1(self.layer_1(self.act_0(self.layer_0(x))))

Напишем для неё Loss-функцию

(подсказка: вспомните logistic regression)

In [267]:
class NLLLoss(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, y_pred, y_true):
        return (-(y_true * torch.log(y_pred ) + (1 - y_true) * torch.log(1 - y_pred))).mean()


Повторим цикл обучения для новой сети!

In [268]:
model = NNClassifier()
criterion = nn.NLLLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-3)

#model.to("cuda")
model

NNClassifier(
  (layer_0): Linear(in_features=784, out_features=100, bias=True)
  (act_0): Tanh()
  (layer_1): Linear(in_features=100, out_features=1, bias=True)
  (act_1): Tanh()
)

In [ ]:
# create train loop

In [269]:
y_hat = model(X_train_tensor[:10].reshape(10,-1))
y_hat

tensor([[ 0.0647],
        [ 0.0811],
        [ 0.1420],
        [ 0.0708],
        [ 0.2041],
        [ 0.0976],
        [ 0.0355],
        [-0.0449],
        [ 0.0541],
        [ 0.0051]], grad_fn=<TanhBackward0>)

In [270]:
y_train_tensor[:10]

tensor([0., 1., 1., 1., 0., 1., 1., 1., 1., 1.])

In [271]:
y_hat[:,0].shape, y_train_tensor[:10].shape

(torch.Size([10]), torch.Size([10]))

In [272]:
criterion(y_hat[:, 0], y_train_tensor[:10].type(torch.long))

tensor(-0.0647, grad_fn=<NllLossBackward0>)

In [273]:
for idx in range(50000):
    y_hat = model(X_train_tensor[:10000].reshape(10000, -1))
    L = criterion(y_hat[:, 0],  y_train_tensor[:10000].type(torch.long))
    L.backward()
    optimizer.step()
    optimizer.zero_grad()
    if idx % 100 == 0:
        print(f"Current Loss: {L}")
    break

Current Loss: -0.06473998725414276
